columns:
  coins_spent:
    default: 0.0
    dtype: float32
  device_os:
    default: N/A
    dtype: string
  distance_avg:
    default: 0.0
    dtype: float32
  event_id:
    default: N/A
    dtype: string
  event_timestamp:
    default: N/A
    dtype: string
  game_day:
    default: 0.0
    dtype: float32
  geo_country:
    default: N/A
    dtype: string
  is_powerup_clicked:
    default: 0
    dtype: int32
  last_run_end_reason:
    default: N/A
    dtype: string
  presented_powerup:
    default: N/A
    dtype: string
data:
  balanced_shuffle_buffer_size: 5000
  batch_size: 128
  compression_type: GZIP
  data_file_path: data/raw/nano_iap_purchases.csv.gz
  eval_data_file_path: data/raw/validation.csv
  field_delim: ','
  ingest_batch_size: 1
  ingest_buffer_size: 1
  ingest_epochs: 1
  ingest_shuffle: false
  shuffle_buffer_size: 5000
  test_data_file_path: data/raw/test.csv
  train_data_file_path: data/raw/training.csv
evaluation:
  validation_callback:
    downsample_actions: true
    downsample_seed: 42
    enabled: true
    filter_positive_rewards: true
    max_batches: 100
features:
  action_weight_column: presented_powerup
  feature_types:
    categorical:
    - geo_country
    - device_os
    - last_run_end_reason
    numerical:
    - distance_avg
    - coins_spent
    - game_day
  label_column: is_powerup_clicked
  unwanted_cols:
  - event_timestamp
  - event_id
model_export:
  checkpoints:
    enabled: true
    mode: min
    monitor: val_loss
    save_best_only: true
  model_directory: data/artifacts/models
  model_summary:
    enabled: true
    expand_nested: true
    line_length: 112
    positions: null
  plotting:
    enabled: true
    expand_nested: true
    rankdir: LR
    show_layer_activations: true
    show_layer_names: true
    show_shapes: true
    show_trainable: true
  save_format: tf
  tflite_enabled: false
  tflite_model_version: v1
training:
  adaption_batch_size: 50000 # Increased to ensure full vocab coverage
  batch_size: 128
  epochs: 20
  initial_learning_rate: 0.001
  lr_decay_rate: 0.7
  lr_decay_steps: 1000
  lr_staircase: true
  steps_per_epoch: 5468 # 700,000 / 128 ~= 5468
  loss_function: "focal" # "mse" or "focal"
  focal_loss_gamma: 2.0
  focal_loss_alpha: 0.25
